### ISSUE TITLE
Status page for current health of the server.

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#15]
[Moved from GitLab]

**Comment by MridulS** [comment]
https://github.com/cstate/cstate

**Comment by arnim** [comment]
https://cstate.mnts.lt/ looks nice ;)

**Comment by MridulS** [comment]
https://mriduls.github.io/test_status_page/ a test implementation for the status page. Everything runs on the GitHub infrastructure through GH actions.

**Comment by MridulS** [comment]
The status page is up and running at https://gesisnotebooks.github.io/status/ , people can also subscribe to the issue list at https://github.com/gesisnotebooks/status  by "watching" the repo.

The status page is also part of https://gesiswts.github.io/uptime/

**Comment by arnim** [comment]
there is also a
```
# [📈 Live Status](https://MridulS.github.io/test_status_page)
```
in https://github.com/gesisnotebooks/status/blob/master/README.md
