### ISSUE TITLE
Docker registry service failing

### ISSUE THREAD

**Issue by arnim** [gesiscss/orc#20]
# Binder health checks failing

Binder [health checks](https://notebooks.gesis.org/binder/health) failing since [yesterday 23:00](https://notebooks.gesis.org/grafana/d/nDQPwi7mk/node-activity?viewPanel=26&orgId=1&from=1606475389321&to=1606556684725)

```javascript
// 20201128110613
// https://notebooks.gesis.org/binder/health

{
  "ok": false,
  "checks": [
    {
      "service": "Docker registry",
      "ok": false
    },
    {
      "service": "JupyterHub API",
      "ok": true
    },
    {
      "service": "Pod quota",
      "ok": true,
      "total_pods": 8,
      "build_pods": 0,
      "user_pods": 8,
      "quota": 200
    }
  ]
}
```

**Comment by MridulS** [comment]
Restarted the pods, looks okay for now.
Need to figure out what's happening here.

**Comment by arnim** [comment]
Thank's for the quick-fix :bug: :+1:

**Comment by arnim** [comment]
It started to fail again in about 50% of the cases. Interestingly only the [health of the public binder](https://notebooks.gesis.org/binder/health) is affected but seemingly not the [persistent binderhub](https://notebooks.gesis.org/services/binder/health).

**Comment by MridulS** [comment]
yeah it never really fails on persistent one.

**Comment by MridulS** [comment]
closing this, until next time.
