### ISSUE TITLE
NodeNotReady failure on one of the nodes.

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#21]
One of the nodes went down and the status of the node on `kubectl get nodes` was `NotReady`.

To get a better overview of the error, use the describe function.
`kubectl describe nodes` output:

```
  Ready                False   Sun, 06 Dec 2020 18:56:49 +0100   Sun, 06 Dec 2020 18:49:40 +0100   KubeletNotReady              PLEG is not healthy: pleg was last seen active 10m18.040734348s ago; threshold is 3m0s
```

The PLEG health checks depend on robustness of docker on the particular server (https://github.com/kubernetes/kubernetes/issues/45419) but everything looked okay after checking the usual docker commands, `docker ps`, `docker images`, etc.

To solve this I did a restart of the docker service, `systemctl restart docker` and that worked to bring the node up.

There is an underlying docker bug/issue here that needs to be fixed. (Not sure if it's related to the recent changes to DockerHub)

**Comment by faflo** [comment]
not sure if this relates to the 503 "Under Maintenance" if been getting since yesterday and am still getting right now when trying to access my (logged in) persistent servers.

**Comment by MridulS** [comment]
Yeah, I'm redeploying the cluster right now and should be back up in a couple of hours.

**Comment by MridulS** [comment]
@faflo it should be back up.

**Comment by faflo** [comment]
"Vom Feinsten"! ;) Thanks

**Comment by MridulS** [comment]
Closing this, until the next time.
