### ISSUE TITLE
Docker will be deprecated as an underlying CR, we need to move to another CRI

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#26]
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

**Comment by manics** [comment]
As far as BinderHub is concerned Docker is needed for the repo2docker build pod. There's some [exploratory work on using other container builders](https://github.com/jupyterhub/repo2docker/pull/848).

**Comment by MridulS** [comment]
https://github.com/jupyterhub/binderhub/issues/1228 relevant discussion.

**Comment by MridulS** [comment]
notebooks-test.gesis.org now uses containerd underneath as the container runtime.
Things to keep in mind while doing this: https://github.com/jupyterhub/binderhub/issues/1228#issuecomment-744008333

In terms of changing the CR, it doesn't look like there is a straight forward swapping method between CR. Need to clean up the cluster with `kubeadm reset`, delete all old config, remove `docker`, reboot the servers, [install containerd](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd) and then follow the usual process of bringing up a k8s cluster minus the docker installation part. 

NOTE: need to make sure the interaction the dind works with authenticated docker session (rate limit).

**Comment by MridulS** [comment]
moved to containerd with dind.
