### ISSUE TITLE
FAQ persistent launch link doku

### ISSUE THREAD

**Issue by arnim** [gesiscss/orc#31]
The FAQs don't seem to contain a docu on how to "create" a launch link for the persistent BH along the lines of

![image](https://user-images.githubusercontent.com/265541/107388834-84f3c780-6af6-11eb-8d1e-77e8864ec589.png)

Let's create a Q for this.

**Comment by MridulS** [comment]
added in https://github.com/gesiscss/orc/commit/e255fef0031550c8a0b2e26d6961e3e0dec9ac00
