### ISSUE TITLE
Support for persistence with non-jovyan users in dockerfile based repositories 

### ISSUE THREAD

**Issue by arnim** [gesiscss/orc#33]
Currently, persistence is not not possible with non-jovyan users in dockerfile based repositories. We should enable this via persistent_binderhub (potentially also have an issue over there). Maybe we should also have a look at how [tljh-repo2docker](https://github.com/plasmabio/tljh-repo2docker) does it.

**Comment by MridulS** [comment]
Relevant issue https://github.com/gesiscss/persistent_binderhub/issues/4
Let's keep this issue at persistent_binderhub.
