### ISSUE TITLE
Add the sharing URL as part of the project form.

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#39]
"Fill in the fields to see a URL for sharing your Binder"

Currently users need to manually construct the URLs if they want to share the URL, we should do the same thing like mybinder so automatically construct the links. (with a "launch with GESIS notebooks button)

**Comment by MridulS** [comment]
Something like [![GESIS Notebooks](https://img.shields.io/badge/Launch-GESIS%20Notebooks-brightgreen)]()

**Comment by arnim** [comment]
The fields are already there in "url row" & "badges row" ;)

**Comment by MridulS** [comment]
Should be taken care by https://github.com/gesiscss/persistent_binderhub/issues/7
