### ISSUE TITLE
Potential CSS problem

### ISSUE THREAD

**Issue by arnim** [gesiscss/orc#7]
Persistent[1] and regular[2] launch lead to different looking Lab views. Maybe this is a CSS issue.

1) https://notebooks.gesis.org/services/binder/v2/gh/Galadirith/learn-github/master?urlpath=lab/tree/learn-github/1-introduction.ipynb

![Screenshot_2020-05-20_20-55-38](https://user-images.githubusercontent.com/265541/82485831-4b98a900-9adc-11ea-833e-44d8b517ab0a.png)

2) https://notebooks.gesis.org/binder/v2/gh/Galadirith/learn-github/master?urlpath=lab/tree/learn-github/1-introduction.ipynb

![Screenshot_2020-05-20_20-57-35](https://user-images.githubusercontent.com/265541/82486017-8ef31780-9adc-11ea-9ed2-62a335bdfde4.png)

**Comment by bitnik** [comment]
i have just tested this and for me they look the same (as it is in your second pic). could you check it again?

**Comment by arnim** [comment]
I think this might be something related to versioning & browser caching. If I clear the cash it's gone.

**Comment by MridulS** [comment]
Closing this, as it looks like it was cache issue.
